# This file was generated by GoReleaser. DO NOT EDIT.
cask "functy" do
  version "0.8.1"

  on_macos do
    on_intel do
      sha256 "39134ddfd99c5f5febd6d7c3ff52b88ee3e65c55e7b78a5181c3e9d856cac145"
      url "https://github.com/tsarna/functy/releases/download/v#{version}/functy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "77b9bf9c14377d3122886cb1a8377ec27988f3a16aeb85fdc6ba205a1cb3d3eb"
      url "https://github.com/tsarna/functy/releases/download/v#{version}/functy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "83f31fa55fd77f9aadecf56e3fc7a395d0a557a7594203ccada4f5bcf0b7bdb4"
      url "https://github.com/tsarna/functy/releases/download/v#{version}/functy_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "51cdbb68c8ed48913a63ad6c7125eda9e55dd0c620ad978bc5d295f3a8f2a64c"
      url "https://github.com/tsarna/functy/releases/download/v#{version}/functy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "functy"
  desc "Run and check functy (.cty) source files"
  homepage "https://github.com/tsarna/functy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "functy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/functy"]
    end
  end

  # No zap stanza required

end
