# This file was generated by GoReleaser. DO NOT EDIT.
cask "functy" do
  version "0.14.0"

  on_macos do
    on_intel do
      sha256 "b67dc5fe6b737bf7c949afa1490a5db93e2ea7ef2c80c1f3325484744e1f52e6"
      url "https://github.com/tsarna/functy/releases/download/v#{version}/functy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7bb230c81c402ccc485ecc1565572348644213562fa7fbcd15044c6bc4d5c99a"
      url "https://github.com/tsarna/functy/releases/download/v#{version}/functy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "316035f7bb50932f3a8b2e922e530f0ee2e9b47a43efcdcdd50ed155aca7f008"
      url "https://github.com/tsarna/functy/releases/download/v#{version}/functy_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0d39d944af4658abe6cd3a76b32056cea7a3af4cc927f8acc9a609625614fcaf"
      url "https://github.com/tsarna/functy/releases/download/v#{version}/functy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "functy"
  desc "Run and check functy (.cty) source files"
  homepage "https://github.com/tsarna/functy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "functy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/functy"]
    end
  end

  # No zap stanza required

end
