# This file was generated by GoReleaser. DO NOT EDIT.
cask "functy" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "46238668cb87b86301179945cef411f191a36713ee1a6d66007adbb39598321f"
      url "https://github.com/tsarna/functy/releases/download/v#{version}/functy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c3aefdafe19c2a3d939454b7899cf9b4fc795a28f75026ad2596c2b6ea109e54"
      url "https://github.com/tsarna/functy/releases/download/v#{version}/functy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9d5e2115109ef91a2243c98426f6e012ea8c3e453133e36dd60db893184a281e"
      url "https://github.com/tsarna/functy/releases/download/v#{version}/functy_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "874102746ff096208f092ee5f241db97dcc804c79fb71e31608c5ff263ca54a1"
      url "https://github.com/tsarna/functy/releases/download/v#{version}/functy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "functy"
  desc "Run and check functy (.cty) source files"
  homepage "https://github.com/tsarna/functy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "functy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/functy"]
    end
  end

  # No zap stanza required

end
