# This file was generated by GoReleaser. DO NOT EDIT.
cask "vinculum" do
  version "0.45.1"

  on_macos do
    on_intel do
      sha256 "29ea1a08b873f6f1b9ba55e2d2db663a26419b543bee533d4330b74ce2eb488e"
      url "https://github.com/tsarna/vinculum/releases/download/v#{version}/vinculum_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "36c8f49677373c7612e2f9774e7f6452408f851101cbfd482c2827d0df0c9cbd"
      url "https://github.com/tsarna/vinculum/releases/download/v#{version}/vinculum_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "691faa139ad1cbbd2bb1e0e85d0525807522f434587d9a0cd4901c4e44b5c7c2"
      url "https://github.com/tsarna/vinculum/releases/download/v#{version}/vinculum_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9e1bd4600667c53e6f27bbde718b101040791babf0389083c971660de16eaa52"
      url "https://github.com/tsarna/vinculum/releases/download/v#{version}/vinculum_#{version}_linux_arm64.tar.gz"
    end
  end

  name "vinculum"
  desc "No-code protocol bridging and message routing configured in HCL"
  homepage "https://github.com/tsarna/vinculum"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vinculum"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vinculum"]
    end
  end

  # No zap stanza required

end
