# This file was generated by GoReleaser. DO NOT EDIT.
cask "vinculum" do
  version "0.45.0"

  on_macos do
    on_intel do
      sha256 "f1bebcc4d04e445519715298e1151d5564dc8ee1716494c34ad0d2b9105eb527"
      url "https://github.com/tsarna/vinculum/releases/download/v#{version}/vinculum_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fa6455ed7d84aee6c14882d4ae1e7bda4d158dce16d90c485356cabad9b17aaa"
      url "https://github.com/tsarna/vinculum/releases/download/v#{version}/vinculum_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "04432b094bf6cdfb72c094c4cee6b1646ef8d24fb588dca1d2a494e5572ac3b8"
      url "https://github.com/tsarna/vinculum/releases/download/v#{version}/vinculum_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7b62738c8756a85a51c250e109496cf9d84041cac5a6b1f707cefab67cb150ae"
      url "https://github.com/tsarna/vinculum/releases/download/v#{version}/vinculum_#{version}_linux_arm64.tar.gz"
    end
  end

  name "vinculum"
  desc "No-code protocol bridging and message routing configured in HCL"
  homepage "https://github.com/tsarna/vinculum"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vinculum"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vinculum"]
    end
  end

  # No zap stanza required

end
